import {
  AccessAuditStat,
  AccessAuditLogRow,
  AuditInsightItem,
  SuspiciousTrendItem,
  ComplianceReminderItem,
} from './accessAuditTypes';

export const mockAccessAuditStats: AccessAuditStat = {
  totalEventsToday: 342,
  totalEventsTrend: '↑ 14%',
  totalEventsSub: 'Across all departments',
  standardAccesses: 318,
  standardAccessesTrend: '↑ 12%',
  standardAccessesSub: 'Routine patient record views',
  flaggedEvents: 24,
  flaggedEventsTrend: '↑ 33%',
  flaggedEventsSub: 'Requires review',
  activeSessions: 56,
  activeSessionsTrend: '↑ 8%',
  activeSessionsSub: 'Users currently accessing records',
};

export const mockFilterOptions = {
  dateRanges: [
    'Jun 5, 2025 – Jun 12, 2025',
    'Today (Jun 12, 2025)',
    'Yesterday (Jun 11, 2025)',
    'Last 7 Days',
    'Last 30 Days',
    'Custom Range...',
  ],
  users: [
    'All Users',
    'Dr. Amit Verma',
    'Nurse Sarah Wilson',
    'Dr. Kavita Rao',
    'IT Support (Rohan)',
    'Dr. Vikram Singh',
    'Admin (Priya Nair)',
    'Dr. Neha Kapoor',
    'Nurse Emily Carter',
  ],
  departments: [
    'All Departments',
    'Cardiology',
    'General Medicine',
    'Neurology',
    'IT',
    'Emergency',
    'Administration',
    'Radiology',
    'Pediatrics',
    'Orthopedics',
  ],
  accessTypes: [
    'All Access Types',
    'View',
    'Export',
    'Edit',
    'Print',
  ],
};

export const mockAuditLogs: AccessAuditLogRow[] = [
  {
    id: 'log-001',
    index: 1,
    user: 'Dr. Amit Verma',
    role: 'Cardiologist',
    patientRecord: '#45872 (John D. Smith)',
    patientId: '#45872',
    patientName: 'John D. Smith',
    accessType: 'View',
    reason: 'Patient consultation',
    timestamp: 'Jun 12, 2025 09:24 AM',
    duration: '4m 12s',
    department: 'Cardiology',
    status: 'Standard',
    ipAddress: '192.168.1.104',
    deviceId: 'WS-CARD-04',
    hash: 'SHA256:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
  },
  {
    id: 'log-002',
    index: 2,
    user: 'Nurse Sarah Wilson',
    role: 'Registered Nurse',
    patientRecord: '#27631 (Mary L. Chen)',
    patientId: '#27631',
    patientName: 'Mary L. Chen',
    accessType: 'View',
    reason: 'Treatment administration',
    timestamp: 'Jun 12, 2025 08:17 AM',
    duration: '2m 08s',
    department: 'General Medicine',
    status: 'Standard',
    ipAddress: '192.168.1.112',
    deviceId: 'TB-NURSE-09',
    hash: 'SHA256:9c8a2b53147ef5c98a3b610c4d8e5f2a1b9c7d4e3f1a2b5c8d7e4f1a9b2c3d4e',
  },
  {
    id: 'log-003',
    index: 3,
    user: 'Dr. Kavita Rao',
    role: 'Neurologist',
    patientRecord: '#88214 (Robert K. Lee)',
    patientId: '#88214',
    patientName: 'Robert K. Lee',
    accessType: 'View',
    reason: 'Follow-up review',
    timestamp: 'Jun 12, 2025 07:56 AM',
    duration: '3m 45s',
    department: 'Neurology',
    status: 'Standard',
    ipAddress: '192.168.2.45',
    deviceId: 'WS-NEUR-02',
    hash: 'SHA256:1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
  },
  {
    id: 'log-004',
    index: 4,
    user: 'IT Support (Rohan)',
    role: 'IT Staff',
    patientRecord: '#63901 (Emma T. White)',
    patientId: '#63901',
    patientName: 'Emma T. White',
    accessType: 'View',
    reason: 'System support',
    timestamp: 'Jun 12, 2025 06:42 AM',
    duration: '6m 21s',
    department: 'IT',
    status: 'Standard',
    ipAddress: '10.0.4.88',
    deviceId: 'IT-ADMIN-SRV',
    hash: 'SHA256:3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e',
  },
  {
    id: 'log-005',
    index: 5,
    user: 'Dr. Vikram Singh',
    role: 'Emergency Physician',
    patientRecord: '#77123 (Michael B. Carter)',
    patientId: '#77123',
    patientName: 'Michael B. Carter',
    accessType: 'View',
    reason: 'Emergency care',
    timestamp: 'Jun 12, 2025 02:18 AM',
    duration: '8m 14s',
    department: 'Emergency',
    status: 'Flagged',
    ipAddress: '192.168.3.12',
    deviceId: 'ER-ROOM-01',
    flagReason: 'Off-hours patient record access during non-scheduled shift (02:18 AM).',
    hash: 'SHA256:4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a',
  },
  {
    id: 'log-006',
    index: 6,
    user: 'Admin (Priya Nair)',
    role: 'Hospital Administrator',
    patientRecord: '#55109 (Olivia R. Patel)',
    patientId: '#55109',
    patientName: 'Olivia R. Patel',
    accessType: 'View',
    reason: 'Administrative review',
    timestamp: 'Jun 12, 2025 01:03 AM',
    duration: '3m 02s',
    department: 'Administration',
    status: 'Standard',
    ipAddress: '10.0.1.15',
    deviceId: 'ADM-SEC-01',
    hash: 'SHA256:5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b',
  },
  {
    id: 'log-007',
    index: 7,
    user: 'Dr. Neha Kapoor',
    role: 'Neurologist',
    patientRecord: '#66218 (Daniel M. Young)',
    patientId: '#66218',
    patientName: 'Daniel M. Young',
    accessType: 'Export',
    reason: 'Research / Study',
    timestamp: 'Jun 11, 2025 11:42 PM',
    duration: '1m 56s',
    department: 'Neurology',
    status: 'Flagged',
    ipAddress: '192.168.2.89',
    deviceId: 'WS-NEUR-05',
    flagReason: 'Patient history export performed without formal IRB authorization code attached.',
    hash: 'SHA256:6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c',
  },
  {
    id: 'log-008',
    index: 8,
    user: 'Nurse Emily Carter',
    role: 'Registered Nurse',
    patientRecord: '#33901 (Sophia K. Adams)',
    patientId: '#33901',
    patientName: 'Sophia K. Adams',
    accessType: 'View',
    reason: 'Medication review',
    timestamp: 'Jun 11, 2025 08:11 PM',
    duration: '2m 37s',
    department: 'General Medicine',
    status: 'Standard',
    ipAddress: '192.168.1.119',
    deviceId: 'TB-NURSE-04',
    hash: 'SHA256:7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d',
  },
];

export const mockAuditInsights: AuditInsightItem[] = [
  {
    id: 'ins-1',
    label: 'Most Active User',
    value: 'Dr. Amit Verma',
    detail: '48 accesses',
  },
  {
    id: 'ins-2',
    label: 'Most Accessed Department',
    value: 'General Medicine',
    detail: '312 accesses',
  },
  {
    id: 'ins-3',
    label: 'Highest Access Type',
    value: 'Record View',
    detail: '1,102 events',
  },
  {
    id: 'ins-4',
    label: 'After-Hours Accesses',
    value: '86 events',
    detail: '↑ 18%',
    trend: '↑ 18%',
    trendUp: true,
  },
];

export const mockSuspiciousTrends: SuspiciousTrendItem[] = [
  {
    id: 'st-1',
    title: 'Multiple record accesses in short time',
    description: 'Same user, multiple records within 5 minutes',
    count: '6 events',
    trend: '↑ 200%',
  },
  {
    id: 'st-2',
    title: 'Accesses outside normal hours',
    description: 'Occurs between 10 PM – 6 AM',
    count: '12 events',
    trend: '↑ 71%',
  },
  {
    id: 'st-3',
    title: 'Unusual department access',
    description: 'Access to non-primary department records',
    count: '4 events',
    trend: '↑ 100%',
  },
  {
    id: 'st-4',
    title: 'Large data exports',
    description: 'Bulk record exports detected',
    count: '2 events',
    trend: '↑ 100%',
  },
];

export const mockComplianceReminders: ComplianceReminderItem[] = [
  {
    id: 'cr-1',
    title: 'HIPAA Compliance',
    description: 'Maintain audit logs for 6 years',
    status: 'Compliant',
    statusType: 'green',
    iconType: 'check',
  },
  {
    id: 'cr-2',
    title: 'Regular Access Review',
    description: 'Review flagged events weekly',
    status: 'On Track',
    statusType: 'green',
    iconType: 'calendar',
  },
  {
    id: 'cr-3',
    title: 'User Access Certification',
    description: 'Next review due Jul 1, 2025',
    status: 'Scheduled',
    statusType: 'blue',
    iconType: 'user-badge',
  },
  {
    id: 'cr-4',
    title: 'Data Export Monitoring',
    description: 'Monitor and review bulk exports',
    status: 'Active',
    statusType: 'green',
    iconType: 'clock',
  },
];
