import {
  DepartmentItem,
  DepartmentStats,
  DepartmentDistributionItem,
  BedCapacityStats,
  DepartmentUpdateItem,
} from './departmentTypes';

export const mockDepartmentStats: DepartmentStats = {
  totalDepartments: 14,
  totalTrend: '↑ 8%',
  activeHeads: 12,
  activeHeadsTrend: '↑ 9%',
  openRoles: 28,
  openRolesTrend: '↑ 12%',
  performanceScore: 92,
  performanceTrend: '↑ 5%',
};

export const mockDepartments: DepartmentItem[] = [
  {
    id: 'dept-01',
    name: 'Cardiology',
    head: 'Dr. Priya Sharma',
    headAvatar: '/doc_priya_sharma.png',
    doctorsCount: 18,
    staffCount: 42,
    bedCapacity: 40,
    status: 'Active',
    category: 'Clinical',
    location: 'Building A, 3rd Floor',
    description: 'Comprehensive cardiovascular diagnostic and interventional care.',
  },
  {
    id: 'dept-02',
    name: 'Radiology',
    head: 'Dr. Arjun Mehta',
    headAvatar: '/doc_avatar_2.png',
    doctorsCount: 12,
    staffCount: 28,
    bedCapacity: 25,
    status: 'Active',
    category: 'Clinical',
    location: 'Diagnostic Wing, Ground Floor',
    description: 'Advanced MRI, CT Scan, Ultrasound, and X-Ray imaging services.',
  },
  {
    id: 'dept-03',
    name: 'Neurology',
    head: 'Dr. Neha Kapoor',
    headAvatar: '/doc_avatar_3.png',
    doctorsCount: 10,
    staffCount: 26,
    bedCapacity: 30,
    status: 'Active',
    category: 'Clinical',
    location: 'Building B, 2nd Floor',
    description: 'Specialized neurological assessments, stroke unit, and neuro-ICU care.',
  },
  {
    id: 'dept-04',
    name: 'Emergency Medicine',
    head: 'Dr. Sameer Khan',
    headAvatar: '/doc_avatar_4.png',
    doctorsCount: 24,
    staffCount: 56,
    bedCapacity: 50,
    status: 'Active',
    category: 'Clinical',
    location: 'Emergency Trauma Centre, Ground Floor',
    description: '24/7 Level 1 Trauma & Resuscitation Center with dedicated triage.',
  },
  {
    id: 'dept-05',
    name: 'General Medicine',
    head: 'Dr. Ananya Iyer',
    headAvatar: '/doc_avatar_5.png',
    doctorsCount: 20,
    staffCount: 48,
    bedCapacity: 60,
    status: 'Active',
    category: 'Clinical',
    location: 'Building A, 1st Floor',
    description: 'Internal medicine, chronic illness management, and multi-system care.',
  },
  {
    id: 'dept-06',
    name: 'Pediatrics',
    head: 'Dr. Rohit Desai',
    headAvatar: '/doc_avatar_6.png',
    doctorsCount: 14,
    staffCount: 36,
    bedCapacity: 40,
    status: 'Active',
    category: 'Clinical',
    location: 'Children’s Pavilion, 2nd Floor',
    description: 'Pediatric intensive care, neonatal unit, and child wellness.',
  },
  {
    id: 'dept-07',
    name: 'Orthopedics',
    head: 'Dr. Kavita Rao',
    headAvatar: '/doc_avatar_7.png',
    doctorsCount: 16,
    staffCount: 32,
    bedCapacity: 40,
    status: 'Active',
    category: 'Clinical',
    location: 'Surgical Block, 3rd Floor',
    description: 'Joint replacement, spine surgery, trauma reconstruction, and sports medicine.',
  },
  {
    id: 'dept-08',
    name: 'Oncology',
    head: 'Dr. Amit Verma',
    headAvatar: '/doc_avatar_8.png',
    doctorsCount: 11,
    staffCount: 28,
    bedCapacity: 35,
    status: 'Inactive',
    category: 'Clinical',
    location: 'Cancer Care Wing, 4th Floor',
    description: 'Medical and radiation oncology services currently under structural renovation.',
  },
  {
    id: 'dept-09',
    name: 'Obstetrics & Gynecology',
    head: 'Dr. Sarah Wilson',
    headAvatar: '/doc_avatar_9.png',
    doctorsCount: 13,
    staffCount: 30,
    bedCapacity: 45,
    status: 'Active',
    category: 'Clinical',
    location: 'Maternity Wing, 1st Floor',
    description: 'Labor delivery suites, prenatal diagnostics, and women’s health.',
  },
  {
    id: 'dept-10',
    name: 'Anesthesiology',
    head: 'Dr. Vikram Singh',
    headAvatar: '/doc_avatar_10.png',
    doctorsCount: 11,
    staffCount: 26,
    bedCapacity: 30,
    status: 'Active',
    category: 'Clinical',
    location: 'Operating Theatre Complex, 2nd Floor',
    description: 'Perioperative care, acute pain management, and surgical anesthesia.',
  },
  {
    id: 'dept-11',
    name: 'Pathology & Diagnostic Labs',
    head: 'Dr. Meera Nambiar',
    doctorsCount: 8,
    staffCount: 24,
    bedCapacity: 0,
    status: 'Active',
    category: 'Support',
    location: 'Central Lab Wing, Basement 1',
    description: 'Automated clinical biochemistry, hematology, and histopathology testing.',
  },
  {
    id: 'dept-12',
    name: 'Pharmacy & Drug Distribution',
    head: 'Rajiv Saxena',
    doctorsCount: 4,
    staffCount: 18,
    bedCapacity: 0,
    status: 'Active',
    category: 'Support',
    location: 'Main Concourse, Ground Floor',
    description: 'Inpatient and outpatient pharmaceutical inventory and drug safety dispensing.',
  },
  {
    id: 'dept-13',
    name: 'Hospital Administration & Billing',
    head: 'Rajesh Kumar',
    doctorsCount: 0,
    staffCount: 22,
    bedCapacity: 0,
    status: 'Active',
    category: 'Administrative',
    location: 'Executive Tower, 5th Floor',
    description: 'Hospital operations, health insurance desk, patient admissions, and finance.',
  },
  {
    id: 'dept-14',
    name: 'Biomedical & Facilities Operations',
    head: 'Sunil Sharma',
    doctorsCount: 0,
    staffCount: 16,
    bedCapacity: 0,
    status: 'Active',
    category: 'Facilities',
    location: 'Service Annex, Ground Floor',
    description: 'Medical gas pipeline maintenance, biomedical equipment calibration, and safety.',
  },
];

export const mockDepartmentDistribution: DepartmentDistributionItem[] = [
  {
    name: 'Clinical Departments',
    count: 8,
    percentage: 57,
    color: '#0066FF',
  },
  {
    name: 'Support Services',
    count: 3,
    percentage: 21,
    color: '#00C5FF',
  },
  {
    name: 'Administrative',
    count: 2,
    percentage: 14,
    color: '#8B5CF6',
  },
  {
    name: 'Facilities & Operations',
    count: 1,
    percentage: 7,
    color: '#F59E0B',
  },
];

export const mockBedCapacity: BedCapacityStats = {
  totalBeds: 395,
  totalTrend: '↑ 12%',
  occupiedBeds: 312,
  occupiedPercentage: 79,
  availableBeds: 83,
  availablePercentage: 21,
};

export const mockDepartmentUpdates: DepartmentUpdateItem[] = [
  {
    id: 'upd-1',
    title: 'Dr. Kavita Rao assigned as Head of Orthopedics',
    timestamp: 'Jun 12, 2025 10:24 AM',
    category: 'Department Head',
    dotColor: 'green',
  },
  {
    id: 'upd-2',
    title: 'Oncology department marked as Inactive',
    timestamp: 'Jun 11, 2025 04:15 PM',
    category: 'Status Change',
    dotColor: 'red',
  },
  {
    id: 'upd-3',
    title: 'New department budget approved for Pediatrics',
    timestamp: 'Jun 10, 2025 11:32 AM',
    category: 'Budget Update',
    dotColor: 'green',
  },
  {
    id: 'upd-4',
    title: '5 new staff positions added in Emergency Medicine',
    timestamp: 'Jun 9, 2025 09:18 AM',
    category: 'Staffing',
    dotColor: 'blue',
  },
];
