import { FullDoctorProfile } from './doctorProfileTypes';

export const mockDefaultDoctorProfile: FullDoctorProfile = {
  hero: {
    id: 'doc-neha-kapoor',
    name: 'Dr. Neha Kapoor',
    avatar: '/doc_neha_kapoor.jpg',
    status: 'Active',
    degrees: 'MBBS, MD (Neurology), DM (Neurology)',
    subRole: 'Neurology Specialist',
    email: 'neha.kapoor@citycarehospital.org',
    phone: '+91 98765 43210',
    hospitalId: 'MED667890',
    licenseNumber: 'MED667890',
    department: 'Neurology',
    specialty: 'Neurology',
    joinDate: 'Jun 15, 2022',
    currentShift: 'Morning (8:00 AM – 4:00 PM)',
    workLocation: 'Main Hospital, 3rd Floor',
    assignedRoles: ['Doctor', 'Department Lead'],
  },
  stats: {
    totalPatients: 1248,
    totalPatientsTrend: '↑ 12%',
    appointmentsThisMonth: 86,
    appointmentsTrend: '↑ 8%',
    appointmentsCompleted: 79,
    appointmentsCancelled: 7,
    activeCaseLoad: 42,
    activeCaseLoadTrend: '↑ 5%',
    patientSatisfaction: 4.8,
    patientSatisfactionMax: 5.0,
    patientSatisfactionTrend: '↑ 6%',
    totalReviews: 324,
    avgConsultationTime: 18,
    avgConsultationTrend: '↓ 12%',
    hospitalAvgConsultation: 22,
  },
  qualifications: [
    {
      id: 'qual-1',
      degree: 'DM (Neurology)',
      institution: 'AIIMS, New Delhi',
      year: '2018',
    },
    {
      id: 'qual-2',
      degree: 'MD (Neurology)',
      institution: 'PGIMER, Chandigarh',
      year: '2014',
    },
    {
      id: 'qual-3',
      degree: 'MBBS',
      institution: "King George's Medical University",
      year: '2011',
    },
  ],
  certifications: [
    {
      id: 'cert-1',
      name: 'Medical Council of India (MCI)',
      number: 'MED667890',
      validUntil: 'Dec 31, 2027',
      status: 'Valid',
    },
    {
      id: 'cert-2',
      name: 'Neurology Specialist Certification',
      number: 'NEU45872',
      validUntil: 'Dec 31, 2026',
      status: 'Valid',
    },
    {
      id: 'cert-3',
      name: 'Advanced Stroke Care Training',
      number: 'ASC77821',
      validUntil: 'Jun 30, 2026',
      status: 'Valid',
    },
    {
      id: 'cert-4',
      name: 'BLS (Basic Life Support)',
      number: 'BLS99231',
      validUntil: 'Mar 15, 2026',
      status: 'Valid',
    },
  ],
  departmentAssignment: {
    primaryDepartment: 'Neurology',
    secondaryDepartments: '—',
    departmentHead: 'Dr. Sameer Khan',
    location: 'Main Hospital, 3rd Floor',
    roomOPD: 'OPD Room 305',
  },
  schedule: [
    {
      day: 'Monday',
      shiftTime: '8:00 AM – 4:00 PM',
      availability: 'Available',
      statusColor: 'green',
    },
    {
      day: 'Tuesday',
      shiftTime: '8:00 AM – 4:00 PM',
      availability: 'Available',
      statusColor: 'green',
    },
    {
      day: 'Wednesday',
      shiftTime: '8:00 AM – 4:00 PM',
      availability: 'Available',
      statusColor: 'green',
    },
    {
      day: 'Thursday',
      shiftTime: '8:00 AM – 4:00 PM',
      availability: 'Available',
      statusColor: 'green',
    },
    {
      day: 'Friday',
      shiftTime: '8:00 AM – 4:00 PM',
      availability: 'Available',
      statusColor: 'green',
    },
    {
      day: 'Saturday',
      shiftTime: 'On Call',
      availability: 'Limited',
      statusColor: 'amber',
    },
    {
      day: 'Sunday',
      shiftTime: 'Off',
      availability: 'Unavailable',
      statusColor: 'red',
    },
  ],
  recentActivity: [
    {
      id: 'act-1',
      dateTime: 'Jun 12, 2025 10:24 AM',
      activity: 'Patient record accessed',
      recordNumber: 'Record #PT88214',
      performedBy: 'Dr. Neha Kapoor',
    },
    {
      id: 'act-2',
      dateTime: 'Jun 11, 2025 04:18 PM',
      activity: 'Prescription updated',
      recordNumber: 'Record #PT77122',
      performedBy: 'Dr. Neha Kapoor',
    },
    {
      id: 'act-3',
      dateTime: 'Jun 10, 2025 09:32 AM',
      activity: 'Lab report viewed',
      recordNumber: 'Record #PT66321',
      performedBy: 'Dr. Neha Kapoor',
    },
    {
      id: 'act-4',
      dateTime: 'Jun 9, 2025 02:11 PM',
      activity: 'Patient note added',
      recordNumber: 'Record #PT55218',
      performedBy: 'Dr. Neha Kapoor',
    },
    {
      id: 'act-5',
      dateTime: 'Jun 8, 2025 11:45 AM',
      activity: 'Appointment completed',
      recordNumber: 'Record #PT44902',
      performedBy: 'Dr. Neha Kapoor',
    },
  ],
  permissions: [
    {
      id: 'perm-1',
      name: 'Patient Records Access',
      status: 'Full Access',
      enabled: true,
    },
    {
      id: 'perm-2',
      name: 'Prescription Management',
      status: 'Enabled',
      enabled: true,
    },
    {
      id: 'perm-3',
      name: 'Lab Results Access',
      status: 'Enabled',
      enabled: true,
    },
    {
      id: 'perm-4',
      name: 'Radiology Reports Access',
      status: 'Enabled',
      enabled: true,
    },
    {
      id: 'perm-5',
      name: 'Department Data Access',
      status: 'Enabled',
      enabled: true,
    },
    {
      id: 'perm-6',
      name: 'System Administration',
      status: 'Not Allowed',
      enabled: false,
    },
    {
      id: 'perm-7',
      name: 'Emergency Access',
      status: 'Enabled',
      enabled: true,
    },
  ],
  performance: {
    totalPatientVisits: 682,
    visitsTrend: '↑ 14%',
    newPatients: 214,
    newPatientsTrend: '↑ 18%',
    followUpVisits: 468,
    followUpTrend: '↑ 12%',
    referralsMade: 36,
    referralsTrend: '↑ 6%',
    patientSatisfaction: '4.8 / 5.0',
    satisfactionTrend: '↑ 6%',
    chartData: [
      { month: 'Jan', visits: 85 },
      { month: 'Feb', visits: 96 },
      { month: 'Mar', visits: 104 },
      { month: 'Apr', visits: 118 },
      { month: 'May', visits: 132 },
      { month: 'Jun', visits: 147 },
    ],
  },
};
