import { DoctorItem, DoctorStats } from './doctorTypes';

export const mockDoctorStats: DoctorStats = {
  totalDoctors: 128,
  totalTrend: '↑ 6%',
  activeDoctors: 112,
  activeTrend: '↑ 5%',
  onLeave: 8,
  inactive: 6,
  inactiveTrend: '↓ 2%',
};

export const mockDoctorDirectory: DoctorItem[] = [
  {
    id: 'doc-01',
    name: 'Dr. Priya Sharma',
    qualification: 'MBBS, MD (Cardiology)',
    specialty: 'Cardiology',
    department: 'Cardiology',
    licenseId: 'MED784521',
    experience: '8 Years',
    status: 'Active',
    joinDate: 'Jan 10, 2022',
    avatar: '/doc_avatar_1.png',
    email: 'priya.sharma@citycarehospital.in',
    phone: '+91 98201 44521',
  },
  {
    id: 'doc-02',
    name: 'Dr. Arjun Mehta',
    qualification: 'MBBS, MD (Radiology)',
    specialty: 'Radiology',
    department: 'Radiology',
    licenseId: 'MED332112',
    experience: '6 Years',
    status: 'Active',
    joinDate: 'Mar 15, 2022',
    avatar: '/doc_avatar_2.png',
    email: 'arjun.mehta@citycarehospital.in',
    phone: '+91 98452 33112',
  },
  {
    id: 'doc-03',
    name: 'Dr. Neha Kapoor',
    qualification: 'MBBS, DM (Neurology)',
    specialty: 'Neurology',
    department: 'Neurology',
    licenseId: 'MED667890',
    experience: '10 Years',
    status: 'Active',
    joinDate: 'Jul 01, 2021',
    avatar: '/doc_avatar_3.png',
    email: 'neha.kapoor@citycarehospital.in',
    phone: '+91 97112 66789',
  },
  {
    id: 'doc-04',
    name: 'Dr. Sameer Khan',
    qualification: 'MBBS, MD (Emergency Medicine)',
    specialty: 'Emergency Medicine',
    department: 'Emergency',
    licenseId: 'MED445678',
    experience: '7 Years',
    status: 'Active',
    joinDate: 'Feb 20, 2023',
    avatar: '/doc_avatar_4.png',
    email: 'sameer.khan@citycarehospital.in',
    phone: '+91 99881 44567',
  },
  {
    id: 'doc-05',
    name: 'Dr. Ananya Iyer',
    qualification: 'MBBS, MD (General Medicine)',
    specialty: 'General Medicine',
    department: 'General Medicine',
    licenseId: 'MED998761',
    experience: '5 Years',
    status: 'Active',
    joinDate: 'Aug 12, 2022',
    avatar: '/doc_avatar_5.png',
    email: 'ananya.iyer@citycarehospital.in',
    phone: '+91 96554 99876',
  },
  {
    id: 'doc-06',
    name: 'Dr. Rohit Verma',
    qualification: 'MBBS, MS (General Surgery)',
    specialty: 'General Surgery',
    department: 'Surgery',
    licenseId: 'MED123456',
    experience: '12 Years',
    status: 'On Leave',
    joinDate: 'Jan 05, 2020',
    avatar: '/doc_avatar_6.png',
    email: 'rohit.verma@citycarehospital.in',
    phone: '+91 98110 12345',
  },
  {
    id: 'doc-07',
    name: 'Dr. Kavita Rao',
    qualification: 'MBBS, MD (Pediatrics)',
    specialty: 'Pediatrics',
    department: 'Pediatrics',
    licenseId: 'MED876543',
    experience: '9 Years',
    status: 'Active',
    joinDate: 'Apr 18, 2021',
    avatar: '/doc_avatar_7.png',
    email: 'kavita.rao@citycarehospital.in',
    phone: '+91 98334 87654',
  },
  {
    id: 'doc-08',
    name: 'Dr. Amit Deshmukh',
    qualification: 'MBBS, MS (Orthopedics)',
    specialty: 'Orthopedics',
    department: 'Orthopedics',
    licenseId: 'MED234567',
    experience: '11 Years',
    status: 'Active',
    joinDate: 'Sep 10, 2020',
    avatar: '/doc_avatar_8.png',
    email: 'amit.deshmukh@citycarehospital.in',
    phone: '+91 98223 23456',
  },
  {
    id: 'doc-09',
    name: 'Dr. Ritu Malhotra',
    qualification: 'MBBS, DGO (Obstetrics & Gynae)',
    specialty: 'Obstetrics & Gynae',
    department: 'Obstetrics & Gynae',
    licenseId: 'MED345678',
    experience: '8 Years',
    status: 'Inactive',
    joinDate: 'Dec 01, 2019',
    avatar: '/doc_avatar_9.png',
    email: 'ritu.malhotra@citycarehospital.in',
    phone: '+91 98771 34567',
  },
  {
    id: 'doc-10',
    name: 'Dr. Faisal Khan',
    qualification: 'MBBS, MD (Anesthesiology)',
    specialty: 'Anesthesiology',
    department: 'Anesthesiology',
    licenseId: 'MED456789',
    experience: '7 Years',
    status: 'Active',
    joinDate: 'May 22, 2022',
    avatar: '/doc_avatar_10.png',
    email: 'faisal.khan@citycarehospital.in',
    phone: '+91 98440 45678',
  },
];
