import {
  EmergencyAuditStat,
  EmergencyAccessEvent,
  CriticalAlertItem,
  PatientNotificationBreakdown,
  EmergencyComplianceItem,
} from './emergencyAuditTypes';

export const mockEmergencyAuditStats: EmergencyAuditStat = {
  emergencyEventsToday: 3,
  emergencyEventsTrend: '↑ 50%',
  emergencyEventsSub: 'vs. previous day',
  activeSessions: 5,
  activeSessionsTrend: '↓ 29%',
  activeSessionsSub: 'Currently active',
  highRiskCases: 2,
  highRiskCasesTrend: '↑ 100%',
  highRiskCasesSub: 'Requires immediate review',
  awaitingReview: 5,
  awaitingReviewTrend: '↑ 67%',
  awaitingReviewSub: 'Pending administrator review',
};

export const mockEmergencyEvents: EmergencyAccessEvent[] = [
  {
    id: 'emg-001',
    user: 'Dr. Vikram Singh',
    role: 'Emergency Physician',
    patientRecord: 'Patient Record #77123',
    patientId: '#77123',
    patientName: 'Michael B. Carter',
    emergencyReason: 'Life-threatening emergency',
    isReasonCritical: true,
    department: 'Emergency',
    isDepartmentCritical: true,
    initiatedOn: 'Jun 12, 2025 02:18 AM',
    expiryTime: 'Jun 12, 2025 06:18 AM',
    auditStatus: 'Under Review',
    severity: 'High',
    ipAddress: '192.168.3.12',
    deviceId: 'ER-CRIT-01',
    clinicalJustification: 'Unresponsive trauma patient admitted via ambulance with suspected intracranial hemorrhage. Immediate break-glass bypass authorized under ER Protocol 4A.',
    notificationStatus: 'Pending Notification',
  },
  {
    id: 'emg-002',
    user: 'Nurse Emily Carter',
    role: 'Senior Registered Nurse',
    patientRecord: 'Patient Record #66218',
    patientId: '#66218',
    patientName: 'Daniel M. Young',
    emergencyReason: 'Patient unconscious',
    isReasonCritical: false,
    department: 'Emergency',
    isDepartmentCritical: false,
    initiatedOn: 'Jun 11, 2025 11:42 PM',
    expiryTime: 'Jun 12, 2025 05:42 AM',
    auditStatus: 'Reviewed',
    severity: 'Medium',
    ipAddress: '192.168.3.24',
    deviceId: 'ER-BAY-03',
    clinicalJustification: 'Patient arrived comatose; critical allergy and previous medication record needed prior to administration of acute reversal agents.',
    notificationStatus: 'Notified',
    reviewNotes: 'Reviewed and confirmed compliant by Dr. Sameer Khan at 06:15 AM.',
  },
  {
    id: 'emg-003',
    user: 'Dr. Rohan Malhotra',
    role: 'Interventional Cardiologist',
    patientRecord: 'Patient Record #33901',
    patientId: '#33901',
    patientName: 'Sophia K. Adams',
    emergencyReason: 'Cardiac arrest',
    isReasonCritical: false,
    department: 'Cardiology',
    isDepartmentCritical: false,
    initiatedOn: 'Jun 11, 2025 08:11 PM',
    expiryTime: 'Jun 12, 2025 02:11 AM',
    auditStatus: 'Reviewed',
    severity: 'Medium',
    ipAddress: '192.168.1.108',
    deviceId: 'CATH-LAB-02',
    clinicalJustification: 'In-hospital acute STEMI arrest; immediate access to baseline ECG and anticoagulant history required during cath-lab prep.',
    notificationStatus: 'Notified',
    reviewNotes: 'Standard clinical emergency procedure verified with cath-lab log.',
  },
  {
    id: 'emg-004',
    user: 'IT Support (Rohan)',
    role: 'Systems Administrator',
    patientRecord: 'Patient Record #63901',
    patientId: '#63901',
    patientName: 'Emma T. White',
    emergencyReason: 'System access support',
    isReasonCritical: false,
    department: 'IT Support',
    isDepartmentCritical: false,
    initiatedOn: 'Jun 11, 2025 06:42 AM',
    expiryTime: 'Jun 11, 2025 02:42 PM',
    auditStatus: 'Expired',
    severity: 'Low',
    ipAddress: '10.0.4.88',
    deviceId: 'IT-SEC-SRV',
    clinicalJustification: 'Database synchronization failover verification requested during scheduled server migration.',
    notificationStatus: 'Not Required',
    reviewNotes: 'Routine system maintenance break-glass session naturally expired without incident.',
  },
  {
    id: 'emg-005',
    user: 'Dr. Priya Sharma',
    role: 'Attending Surgeon',
    patientRecord: 'Patient Record #45872',
    patientId: '#45872',
    patientName: 'John D. Smith',
    emergencyReason: 'Emergency surgery',
    isReasonCritical: false,
    department: 'Surgery',
    isDepartmentCritical: false,
    initiatedOn: 'Jun 10, 2025 10:15 PM',
    expiryTime: 'Jun 11, 2025 04:15 AM',
    auditStatus: 'Reviewed',
    severity: 'Medium',
    ipAddress: '192.168.4.15',
    deviceId: 'OT-SUITE-04',
    clinicalJustification: 'Ruptured appendicitis with acute peritonitis. Patient incapacitated under anesthesia.',
    notificationStatus: 'Notified',
    reviewNotes: 'Confirmed by surgical board. Consent proxy verified post-op.',
  },
  {
    id: 'emg-006',
    user: 'Dr. Ananya Iyer',
    role: 'Trauma Specialist',
    patientRecord: 'Patient Record #99321',
    patientId: '#99321',
    patientName: 'Kabir Sengupta',
    emergencyReason: 'Trauma - MVA',
    isReasonCritical: true,
    department: 'Emergency',
    isDepartmentCritical: true,
    initiatedOn: 'Jun 10, 2025 07:33 PM',
    expiryTime: 'Jun 11, 2025 01:33 AM',
    auditStatus: 'Under Review',
    severity: 'High',
    ipAddress: '192.168.3.05',
    deviceId: 'ER-RESUS-01',
    clinicalJustification: 'Multiple vehicle collision polytrauma. Patient identity verified via biometric Health ID scan.',
    notificationStatus: 'Notification Failed',
  },
];

export const mockCriticalAlerts: CriticalAlertItem[] = [
  {
    id: 'ca-1',
    user: 'Dr. Vikram Singh',
    patientRecord: 'Patient Record #77123',
    timestamp: 'Jun 12, 2025 02:18 AM',
    severity: 'High',
    alertType: 'Requires immediate review',
    alertColor: 'red',
    eventId: 'emg-001',
  },
  {
    id: 'ca-2',
    user: 'Dr. Ananya Iyer',
    patientRecord: 'Patient Record #99321',
    timestamp: 'Jun 10, 2025 07:33 PM',
    severity: 'High',
    alertType: 'Extended access duration',
    alertColor: 'red',
    eventId: 'emg-006',
  },
  {
    id: 'ca-3',
    user: 'Nurse Sarah Wilson',
    patientRecord: 'Patient Record #82765',
    timestamp: 'Jun 9, 2025 11:20 PM',
    severity: 'Medium',
    alertType: 'Missing justification',
    alertColor: 'amber',
  },
];

export const mockPatientNotificationStatus: PatientNotificationBreakdown = {
  totalEvents: 18,
  items: [
    {
      status: 'Notified',
      count: 11,
      percentage: 61,
      color: '#10B981', // green
    },
    {
      status: 'Pending Notification',
      count: 4,
      percentage: 22,
      color: '#F59E0B', // amber
    },
    {
      status: 'Notification Failed',
      count: 1,
      percentage: 6,
      color: '#EF4444', // red
    },
    {
      status: 'Not Required',
      count: 2,
      percentage: 11,
      color: '#94A3B8', // slate
    },
  ],
};

export const mockEmergencyComplianceItems: EmergencyComplianceItem[] = [
  {
    id: 'cmp-1',
    title: 'Emergency access reason captured',
    status: 'Compliant',
  },
  {
    id: 'cmp-2',
    title: 'Time-limited access (auto-expiry)',
    status: 'Compliant',
  },
  {
    id: 'cmp-3',
    title: 'Administrator review process',
    status: 'Active',
  },
  {
    id: 'cmp-4',
    title: 'Patient notification workflow',
    status: 'Active',
  },
  {
    id: 'cmp-5',
    title: 'Audit trail immutable',
    status: 'Compliant',
  },
  {
    id: 'cmp-6',
    title: 'Regular compliance reporting',
    status: 'Compliant',
  },
];
