import {
  DoctorVerificationItem,
  AccessAuditItem,
  DepartmentMetric,
  StaffRoleCount,
  EmergencyAlertItem,
  ComplianceStatusItem,
  MetricStat,
} from './types';

export const mockMetricStats: MetricStat[] = [
  {
    id: 'total-doctors',
    title: 'Total Doctors',
    value: '128',
    trend: '↑ 12%',
    trendDirection: 'up',
    trendColor: 'green',
    subtext: 'Across all departments',
    iconType: 'stethoscope',
  },
  {
    id: 'pending-verifications',
    title: 'Pending Verifications',
    value: '8',
    trend: '↑ 2',
    trendDirection: 'up',
    trendColor: 'red',
    subtext: 'Awaiting review',
    iconType: 'pending',
  },
  {
    id: 'active-departments',
    title: 'Active Departments',
    value: '12',
    trend: '—',
    trendDirection: 'neutral',
    trendColor: 'neutral',
    subtext: 'Out of 14 planned',
    iconType: 'department',
  },
  {
    id: 'staff-members',
    title: 'Staff Members',
    value: '342',
    trend: '↑ 6%',
    trendDirection: 'up',
    trendColor: 'green',
    subtext: 'Admins, clinical & support',
    iconType: 'staff',
  },
  {
    id: 'access-requests',
    title: "Today's Access Requests",
    value: '24',
    trend: '↑ 14%',
    trendDirection: 'up',
    trendColor: 'green',
    subtext: 'System record accesses',
    iconType: 'access',
  },
  {
    id: 'emergency-events',
    title: 'Emergency Access Events',
    value: '3',
    trend: '↑ 1',
    trendDirection: 'up',
    trendColor: 'red',
    subtext: 'Requires review',
    iconType: 'emergency',
  },
];

export const mockDoctorVerificationQueue: DoctorVerificationItem[] = [
  {
    id: 'DOC-VERIF-01',
    doctorName: 'Dr. Priya Sharma',
    specialty: 'Cardiology',
    licenseId: 'MED784521',
    department: 'Cardiology',
    submittedOn: 'Jun 11, 2025',
    status: 'Pending',
    email: 'priya.sharma@citycare.org',
    phone: '+91 98201 44521',
    experience: '9 Years',
    qualification: 'MD (Cardiology), AIIMS New Delhi',
  },
  {
    id: 'DOC-VERIF-02',
    doctorName: 'Dr. Arjun Mehta',
    specialty: 'Radiology',
    licenseId: 'MED332112',
    department: 'Radiology',
    submittedOn: 'Jun 10, 2025',
    status: 'Pending',
    email: 'arjun.mehta@citycare.org',
    phone: '+91 98452 33112',
    experience: '6 Years',
    qualification: 'MD (Radio-diagnosis), CMC Vellore',
  },
  {
    id: 'DOC-VERIF-03',
    doctorName: 'Dr. Neha Kapoor',
    specialty: 'Neurology',
    licenseId: 'MED667890',
    department: 'Neurology',
    submittedOn: 'Jun 9, 2025',
    status: 'Pending',
    email: 'neha.kapoor@citycare.org',
    phone: '+91 97112 66789',
    experience: '12 Years',
    qualification: 'DM (Neurology), NIMHANS',
  },
  {
    id: 'DOC-VERIF-04',
    doctorName: 'Dr. Sameer Khan',
    specialty: 'Emergency Medicine',
    licenseId: 'MED445678',
    department: 'Emergency',
    submittedOn: 'Jun 9, 2025',
    status: 'Pending',
    email: 'sameer.khan@citycare.org',
    phone: '+91 99881 44567',
    experience: '8 Years',
    qualification: 'MEM, George Washington Univ / Apollo',
  },
  {
    id: 'DOC-VERIF-05',
    doctorName: 'Dr. Ananya Iyer',
    specialty: 'General Medicine',
    licenseId: 'MED998761',
    department: 'General Medicine',
    submittedOn: 'Jun 8, 2025',
    status: 'Pending',
    email: 'ananya.iyer@citycare.org',
    phone: '+91 96554 99876',
    experience: '5 Years',
    qualification: 'MD (General Medicine), Madras Medical College',
  },
];

export const mockRecentAccessAudit: AccessAuditItem[] = [
  {
    id: 'AUD-01',
    user: 'Dr. Amit Verma',
    accessedRecord: 'Patient Record #45872',
    timestamp: 'Jun 12, 2025 09:24 AM',
    accessType: 'Standard',
  },
  {
    id: 'AUD-02',
    user: 'Nurse Sarah Wilson',
    accessedRecord: 'Patient Record #27631',
    timestamp: 'Jun 12, 2025 08:17 AM',
    accessType: 'Standard',
  },
  {
    id: 'AUD-03',
    user: 'Dr. Kavita Rao',
    accessedRecord: 'Patient Record #88214',
    timestamp: 'Jun 12, 2025 07:56 AM',
    accessType: 'Standard',
  },
  {
    id: 'AUD-04',
    user: 'IT Support (Rohan)',
    accessedRecord: 'Patient Record #63901',
    timestamp: 'Jun 12, 2025 06:42 AM',
    accessType: 'Standard',
  },
  {
    id: 'AUD-05',
    user: 'Dr. Vikram Singh',
    accessedRecord: 'Patient Record #77123',
    timestamp: 'Jun 12, 2025 02:18 AM',
    accessType: 'Emergency',
  },
  {
    id: 'AUD-06',
    user: 'Admin (Priya Nair)',
    accessedRecord: 'Patient Record #55109',
    timestamp: 'Jun 12, 2025 01:03 AM',
    accessType: 'Standard',
  },
];

export const mockDepartmentMetrics: DepartmentMetric[] = [
  { id: 'dep-1', name: 'Cardiology', count: 28, capacity: 40 },
  { id: 'dep-2', name: 'Radiology', count: 24, capacity: 40 },
  { id: 'dep-3', name: 'Emergency', count: 32, capacity: 40 },
  { id: 'dep-4', name: 'Neurology', count: 18, capacity: 40 },
  { id: 'dep-5', name: 'General Medicine', count: 26, capacity: 40 },
];

export const mockStaffRoles: StaffRoleCount[] = [
  { role: 'Administrators', count: 12, color: 'text-blue-500', bgColor: 'bg-blue-100' },
  { role: 'Doctors', count: 128, color: 'text-emerald-500', bgColor: 'bg-emerald-100' },
  { role: 'Nurses', count: 156, color: 'text-purple-500', bgColor: 'bg-purple-100' },
  { role: 'Support Staff', count: 46, color: 'text-amber-500', bgColor: 'bg-amber-100' },
];

export const mockEmergencyAlerts: EmergencyAlertItem[] = [
  {
    id: 'EMERG-01',
    doctorName: 'Dr. Vikram Singh',
    patientRecord: 'Accessed patient record #77123',
    timestamp: 'Jun 12, 2025 02:18 AM',
    status: 'Emergency',
  },
  {
    id: 'EMERG-02',
    doctorName: 'Nurse Emily Carter',
    patientRecord: 'Accessed patient record #66218',
    timestamp: 'Jun 11, 2025 11:42 PM',
    status: 'Emergency',
  },
  {
    id: 'EMERG-03',
    doctorName: 'Dr. Rohan Malhotra',
    patientRecord: 'Accessed patient record #33901',
    timestamp: 'Jun 11, 2025 08:11 PM',
    status: 'Emergency',
  },
];

export const mockComplianceStatus: ComplianceStatusItem[] = [
  { id: 'comp-1', label: 'Two-Factor Authentication', status: 'Enabled', type: 'green' },
  { id: 'comp-2', label: 'Audit Logging', status: 'Active', type: 'green' },
  { id: 'comp-3', label: 'Recent Security Review', status: 'May 2, 2025', type: 'blue' },
  { id: 'comp-4', label: 'Access Controls', status: 'Configured', type: 'green' },
  { id: 'comp-5', label: 'HIPAA Compliance', status: 'Compliant', type: 'green' },
  { id: 'comp-6', label: 'System Uptime', status: '99.9%', type: 'green' },
];
