import {
  NotificationStatMetrics,
  NotificationItem,
  NotificationPreferencesState,
} from './notificationTypes';

export const mockNotificationStats: NotificationStatMetrics = {
  unreadCount: 12,
  unreadTrend: '↑ 33%',
  unreadSub: 'New and unread alerts',
  highPriorityCount: 3,
  highPriorityTrend: '↑ 50%',
  highPrioritySub: 'Require immediate attention',
  verificationUpdatesCount: 8,
  verificationTrend: '↑ 14%',
  verificationSub: 'Doctor/staff verification',
  auditEventsCount: 24,
  auditTrend: '↑ 20%',
  auditSub: 'Access and system activity',
};

export const defaultNotificationPreferences: NotificationPreferencesState = {
  verificationUpdates: true,
  securityAlerts: true,
  accessNotifications: true,
  systemUpdates: true,
  emailNotifications: true,
  pushNotifications: false,
};

export const mockNotificationsList: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Emergency Access Used',
    description: 'Dr. Vikram Singh accessed patient record #77123 due to emergency override.',
    category: 'Access',
    source: 'Access Audit',
    timestamp: 'Jun 12, 2025 02:18 AM',
    priority: 'High',
    isRead: false,
    iconType: 'emergency',
    targetUrl: '/hospital-admin/emergency-access/detail',
    metadata: {
      patientRecord: '#77123',
      doctor: 'Dr. Vikram Singh',
      reason: 'Life-threatening emergency (road traffic trauma)',
    },
  },
  {
    id: 'notif-2',
    title: 'New Doctor Verification Submitted',
    description: 'Dr. Ananya Iyer has submitted their documents for verification.',
    category: 'Verification',
    source: 'Doctor Verification',
    timestamp: 'Jun 11, 2025 04:32 PM',
    priority: 'Medium',
    isRead: false,
    iconType: 'verification-doc',
    targetUrl: '/hospital-admin/doctor-verification',
    metadata: {
      applicant: 'Dr. Ananya Iyer',
      department: 'Cardiology',
      documentsCount: '4 certificates uploaded',
    },
  },
  {
    id: 'notif-3',
    title: 'New Login from Unusual Location',
    description: 'A login attempt was detected from a new location (Mumbai, India).',
    category: 'Security',
    source: 'Security',
    timestamp: 'Jun 11, 2025 01:15 PM',
    priority: 'High',
    isRead: false,
    iconType: 'security-login',
    targetUrl: '/hospital-admin/security-settings',
    metadata: {
      location: 'Mumbai, India',
      ipAddress: '103.22.45.18',
      device: 'Safari on iPhone iOS 18.2',
    },
  },
  {
    id: 'notif-4',
    title: 'Staff Role Updated',
    description: "Nurse Emily Carter's role has been updated to Senior Nurse.",
    category: 'System',
    source: 'Staff Management',
    timestamp: 'Jun 11, 2025 11:42 AM',
    priority: 'Low',
    isRead: true,
    iconType: 'role',
    targetUrl: '/hospital-admin/staff-roles',
    metadata: {
      staffMember: 'Nurse Emily Carter',
      newRole: 'Senior Registered Nurse',
      updatedBy: 'Rajesh Kumar',
    },
  },
  {
    id: 'notif-5',
    title: 'System Maintenance Scheduled',
    description: 'Scheduled maintenance will begin on Jun 14, 2025 at 02:00 AM.',
    category: 'System',
    source: 'System',
    timestamp: 'Jun 11, 2025 10:20 AM',
    priority: 'Low',
    isRead: true,
    iconType: 'maintenance',
    targetUrl: '/hospital-admin/security-settings',
    metadata: {
      maintenanceWindow: 'Jun 14, 2025 02:00 AM – 04:00 AM IST',
      scope: 'Database Index Optimization & Security Patching',
    },
  },
  {
    id: 'notif-6',
    title: 'Multiple Failed Login Attempts',
    description: '5 failed login attempts for user account sarah.wilson@citycare.org.',
    category: 'Security',
    source: 'Security',
    timestamp: 'Jun 10, 2025 09:18 PM',
    priority: 'High',
    isRead: false,
    iconType: 'failed-login',
    targetUrl: '/hospital-admin/security-settings',
    metadata: {
      targetAccount: 'sarah.wilson@citycare.org',
      attemptsCount: '5 failed attempts in 2 minutes',
      actionTaken: 'Account temporarily locked for 15 minutes',
    },
  },
  {
    id: 'notif-7',
    title: 'Verification Approved',
    description: "Dr. Neha Kapoor's verification has been approved.",
    category: 'Verification',
    source: 'Doctor Verification',
    timestamp: 'Jun 10, 2025 03:45 PM',
    priority: 'Medium',
    isRead: true,
    iconType: 'verified-check',
    targetUrl: '/hospital-admin/doctor-verification',
    metadata: {
      doctorName: 'Dr. Neha Kapoor',
      department: 'Pediatrics',
      approvedBy: 'Rajesh Kumar',
    },
  },
  {
    id: 'notif-8',
    title: 'Audit Log Review Required',
    description: 'Unusual access pattern detected for patient records.',
    category: 'Access',
    source: 'Access Audit',
    timestamp: 'Jun 10, 2025 12:10 PM',
    priority: 'Medium',
    isRead: false,
    iconType: 'audit-chart',
    targetUrl: '/hospital-admin/access-audit',
    metadata: {
      pattern: 'Rapid sequential patient record queries',
      affectedRecords: '14 records viewed in 3 minutes',
    },
  },
];
