import { FullRolePermissionsData } from './rolePermissionsTypes';

export const mockDefaultRolePermissions: FullRolePermissionsData = {
  hero: {
    id: 'role-dept-manager',
    name: 'Department Manager',
    description:
      'Can manage department operations, staff, and view relevant reports. Limited system-wide access.',
    assignedStaffCount: 12,
    createdOn: 'May 10, 2024',
    createdBy: 'Rajesh Kumar',
    lastUpdated: 'Jun 5, 2025',
    updatedBy: 'Rajesh Kumar',
    status: 'Active',
  },
  modules: [
    {
      id: 'mod-1',
      moduleName: 'Doctor Management',
      iconType: 'doctor',
      permissions: [
        { id: 'p1-1', label: 'View Doctors', enabled: true },
        { id: 'p1-2', label: 'Add Doctor', enabled: false },
        { id: 'p1-3', label: 'Edit Doctor', enabled: false },
        { id: 'p1-4', label: 'Approve Doctor', enabled: false },
        { id: 'p1-5', label: 'Revoke Access', enabled: false },
        { id: 'p1-6', label: 'Export Data', enabled: false },
      ],
    },
    {
      id: 'mod-2',
      moduleName: 'Department Access',
      iconType: 'department',
      permissions: [
        { id: 'p2-1', label: 'View Departments', enabled: true },
        { id: 'p2-2', label: 'Create Department', enabled: false },
        { id: 'p2-3', label: 'Edit Department', enabled: true },
        { id: 'p2-4', label: 'Delete Department', enabled: false },
        { id: 'p2-5', label: 'Manage Staff', enabled: true },
        { id: 'p2-6', label: 'Export Data', enabled: false },
      ],
    },
    {
      id: 'mod-3',
      moduleName: 'Staff Management',
      iconType: 'staff',
      permissions: [
        { id: 'p3-1', label: 'View Staff', enabled: true },
        { id: 'p3-2', label: 'Add Staff', enabled: true },
        { id: 'p3-3', label: 'Edit Staff', enabled: true },
        { id: 'p3-4', label: 'Deactivate Staff', enabled: false },
        { id: 'p3-5', label: 'Assign Roles', enabled: true },
        { id: 'p3-6', label: 'Export Data', enabled: true },
      ],
    },
    {
      id: 'mod-4',
      moduleName: 'Hospital Profile',
      iconType: 'hospital',
      permissions: [
        { id: 'p4-1', label: 'View Profile', enabled: true },
        { id: 'p4-2', label: 'Edit Profile', enabled: false },
        { id: 'p4-3', label: 'Update Settings', enabled: false },
        { id: 'p4-4', label: 'Manage Billing', enabled: false },
        { id: 'p4-5', label: 'View Licenses', enabled: true },
        { id: 'p4-6', label: 'Export Data', enabled: false },
      ],
    },
    {
      id: 'mod-5',
      moduleName: 'Access Audit Logs',
      iconType: 'audit',
      permissions: [
        { id: 'p5-1', label: 'View Audit Logs', enabled: true },
        { id: 'p5-2', label: 'Filter Logs', enabled: true },
        { id: 'p5-3', label: 'Export Logs', enabled: true },
        { id: 'p5-4', label: 'Delete Logs', enabled: false },
      ],
    },
    {
      id: 'mod-6',
      moduleName: 'Emergency Access Audit',
      iconType: 'emergency',
      permissions: [
        { id: 'p6-1', label: 'View Emergency Access', enabled: true },
        { id: 'p6-2', label: 'Approve Emergency', enabled: false },
        { id: 'p6-3', label: 'Revoke Emergency', enabled: false },
        { id: 'p6-4', label: 'Export Logs', enabled: true },
      ],
    },
    {
      id: 'mod-7',
      moduleName: 'Security Settings',
      iconType: 'security',
      permissions: [
        { id: 'p7-1', label: 'View Security Settings', enabled: false },
        { id: 'p7-2', label: 'Edit Security Settings', enabled: false },
        { id: 'p7-3', label: 'Manage Access Controls', enabled: false },
        { id: 'p7-4', label: 'Two-Factor Settings', enabled: false },
      ],
    },
    {
      id: 'mod-8',
      moduleName: 'Notifications',
      iconType: 'notifications',
      permissions: [
        { id: 'p8-1', label: 'View Notifications', enabled: true },
        { id: 'p8-2', label: 'Send Notifications', enabled: true },
        { id: 'p8-3', label: 'Manage Templates', enabled: false },
        { id: 'p8-4', label: 'Export Data', enabled: false },
      ],
    },
    {
      id: 'mod-9',
      moduleName: 'Reports & Analytics',
      iconType: 'reports',
      permissions: [
        { id: 'p9-1', label: 'View Reports', enabled: true },
        { id: 'p9-2', label: 'Create Reports', enabled: false },
        { id: 'p9-3', label: 'Export Reports', enabled: true },
        { id: 'p9-4', label: 'Schedule Reports', enabled: false },
      ],
    },
  ],
  assignedUsers: [
    {
      id: 'u-1',
      name: 'Dr. Priya Sharma',
      avatar: '/doc_priya_sharma.png',
      department: 'Cardiology',
      status: 'Active',
    },
    {
      id: 'u-2',
      name: 'Dr. Arjun Mehta',
      avatar: '/doc_avatar_2.png',
      department: 'Radiology',
      status: 'Active',
    },
    {
      id: 'u-3',
      name: 'Neha Kapoor',
      avatar: '/doc_neha_kapoor.jpg',
      department: 'Neurology',
      status: 'Active',
    },
    {
      id: 'u-4',
      name: 'Sameer Khan',
      avatar: '/doc_avatar_4.png',
      department: 'Emergency',
      status: 'Active',
    },
    {
      id: 'u-5',
      name: 'Ananya Iyer',
      avatar: '/doc_avatar_5.png',
      department: 'General Medicine',
      status: 'Active',
    },
    {
      id: 'u-6',
      name: 'Vikram Singh',
      avatar: '/doc_avatar_10.png',
      department: 'Orthopedics',
      status: 'Active',
    },
    {
      id: 'u-7',
      name: 'Sarah Wilson',
      avatar: '/doc_avatar_9.png',
      department: 'Pediatrics',
      status: 'Active',
    },
    {
      id: 'u-8',
      name: 'Rohan Patel',
      avatar: '/doc_avatar_8.png',
      department: 'Oncology',
      status: 'Active',
    },
    {
      id: 'u-9',
      name: 'Dr. Kavita Rao',
      avatar: '/doc_avatar_7.png',
      department: 'Neurology',
      status: 'Active',
    },
    {
      id: 'u-10',
      name: 'Rajiv Saxena',
      avatar: '/doc_avatar_6.png',
      department: 'Pharmacy',
      status: 'Active',
    },
    {
      id: 'u-11',
      name: 'Dr. Meera Nambiar',
      avatar: '/doc_avatar_3.png',
      department: 'Pathology',
      status: 'Active',
    },
    {
      id: 'u-12',
      name: 'Sunil Sharma',
      avatar: '/doc_avatar_1.png',
      department: 'Biomedical Operations',
      status: 'Active',
    },
  ],
};
