import {
  StaffMember,
  StaffStats,
  RoleDistributionItem,
  PermissionTemplate,
  RecentRoleChangeItem,
} from './staffRolesTypes';

export const mockStaffStats: StaffStats = {
  totalStaff: 342,
  totalStaffTrend: '↑ 6%',
  roleGroups: 12,
  pendingInvitations: 18,
  pendingInvitationsTrend: '↑ 2',
  activeUsers: 301,
  activeUsersTrend: '↑ 5%',
};

export const mockStaffMembers: StaffMember[] = [
  {
    id: 'staff-1',
    name: 'Dr. Amit Verma',
    avatar: '/doc_avatar_8.png',
    role: 'Consultant Doctor',
    department: 'Cardiology',
    email: 'amit.verma@citycare.org',
    staffId: 'STAFF0012',
    accessLevel: 'Standard',
    status: 'Active',
    lastActive: 'Jun 12, 2025 09:24 AM',
    phone: '+91 98111 22334',
    joinDate: 'Jan 15, 2023',
  },
  {
    id: 'staff-2',
    name: 'Nurse Sarah Wilson',
    avatar: '/doc_avatar_9.png',
    role: 'Staff Nurse',
    department: 'Emergency',
    email: 'sarah.wilson@citycare.org',
    staffId: 'STAFF0045',
    accessLevel: 'Standard',
    status: 'Active',
    lastActive: 'Jun 12, 2025 08:17 AM',
    phone: '+91 98222 33445',
    joinDate: 'Mar 10, 2023',
  },
  {
    id: 'staff-3',
    name: 'Dr. Kavita Rao',
    avatar: '/doc_avatar_7.png',
    role: 'Consultant Doctor',
    department: 'Neurology',
    email: 'kavita.rao@citycare.org',
    staffId: 'STAFF0088',
    accessLevel: 'Elevated',
    status: 'Active',
    lastActive: 'Jun 12, 2025 07:56 AM',
    phone: '+91 98333 44556',
    joinDate: 'Nov 05, 2022',
  },
  {
    id: 'staff-4',
    name: 'IT Support (Rohan)',
    avatar: '/doc_avatar_2.png',
    role: 'IT Support',
    department: 'IT & Systems',
    email: 'rohan.patel@citycare.org',
    staffId: 'STAFF0103',
    accessLevel: 'Admin',
    status: 'Active',
    lastActive: 'Jun 12, 2025 06:42 AM',
    phone: '+91 98444 55667',
    joinDate: 'Aug 20, 2021',
  },
  {
    id: 'staff-5',
    name: 'Dr. Vikram Singh',
    avatar: '/doc_avatar_10.png',
    role: 'Emergency Physician',
    department: 'Emergency',
    email: 'vikram.singh@citycare.org',
    staffId: 'STAFF0077',
    accessLevel: 'Standard',
    status: 'Active',
    lastActive: 'Jun 12, 2025 02:18 AM',
    phone: '+91 98555 66778',
    joinDate: 'Feb 14, 2022',
  },
  {
    id: 'staff-6',
    name: 'Admin (Priya Nair)',
    avatar: '/doc_priya_sharma.png',
    role: 'Hospital Administrator',
    department: 'Administration',
    email: 'priya.nair@citycare.org',
    staffId: 'STAFF0001',
    accessLevel: 'Admin',
    status: 'Active',
    lastActive: 'Jun 12, 2025 01:03 AM',
    phone: '+91 98666 77889',
    joinDate: 'Jul 01, 2020',
  },
  {
    id: 'staff-7',
    name: 'James Carter',
    avatar: '/doc_avatar_4.png',
    role: 'Radiology Technician',
    department: 'Radiology',
    email: 'james.carter@citycare.org',
    staffId: 'STAFF0134',
    accessLevel: 'Standard',
    status: 'Inactive',
    lastActive: 'Jun 10, 2025 11:22 AM',
    phone: '+91 98777 88990',
    joinDate: 'May 12, 2024',
  },
  {
    id: 'staff-8',
    name: 'Ananya Iyer',
    avatar: '/doc_avatar_5.png',
    role: 'Medical Records',
    department: 'Health Information',
    email: 'ananya.iyer@citycare.org',
    staffId: 'STAFF0167',
    accessLevel: 'Standard',
    status: 'Active',
    lastActive: 'Jun 11, 2025 04:35 PM',
    phone: '+91 98888 99001',
    joinDate: 'Sep 25, 2023',
  },
  {
    id: 'staff-9',
    name: 'Dr. Arjun Mehta',
    avatar: '/doc_avatar_2.png',
    role: 'Chief Radiologist',
    department: 'Radiology',
    email: 'arjun.mehta@citycare.org',
    staffId: 'STAFF0023',
    accessLevel: 'Elevated',
    status: 'Active',
    lastActive: 'Jun 12, 2025 11:00 AM',
    phone: '+91 98999 00112',
    joinDate: 'Apr 18, 2021',
  },
  {
    id: 'staff-10',
    name: 'Rajiv Saxena',
    avatar: '/doc_avatar_6.png',
    role: 'Pharmacist Lead',
    department: 'Pharmacy',
    email: 'rajiv.saxena@citycare.org',
    staffId: 'STAFF0211',
    accessLevel: 'Standard',
    status: 'Active',
    lastActive: 'Jun 12, 2025 10:15 AM',
    phone: '+91 98123 45678',
    joinDate: 'Oct 30, 2022',
  },
];

export const mockRoleDistribution: RoleDistributionItem[] = [
  {
    id: 'rd-1',
    role: 'Doctors',
    count: 128,
    percentage: 37,
  },
  {
    id: 'rd-2',
    role: 'Nurses',
    count: 156,
    percentage: 45,
  },
  {
    id: 'rd-3',
    role: 'Support Staff',
    count: 46,
    percentage: 13,
  },
  {
    id: 'rd-4',
    role: 'Administrators',
    count: 12,
    percentage: 5,
  },
];

export const mockPermissionTemplates: PermissionTemplate[] = [
  {
    id: 'pt-1',
    name: 'Standard User',
    description: 'Basic access for clinical staff',
    iconType: 'user',
    color: '#0066FF',
  },
  {
    id: 'pt-2',
    name: 'Elevated User',
    description: 'Extended access for senior clinical staff',
    iconType: 'users',
    color: '#9333EA',
  },
  {
    id: 'pt-3',
    name: 'Department Admin',
    description: 'Department-level administrative access',
    iconType: 'gear',
    color: '#F59E0B',
  },
  {
    id: 'pt-4',
    name: 'System Admin',
    description: 'Full system access and configuration',
    iconType: 'crown',
    color: '#EF4444',
  },
];

export const mockRecentRoleChanges: RecentRoleChangeItem[] = [
  {
    id: 'rc-1',
    staffName: 'Sarah Wilson',
    changeDescription: 'Role updated to Staff Nurse',
    timestamp: 'Jun 12, 2025 09:14 AM',
    dotColor: 'green',
  },
  {
    id: 'rc-2',
    staffName: 'Rohan Patel',
    changeDescription: 'Access level changed to Admin',
    timestamp: 'Jun 11, 2025 04:22 PM',
    dotColor: 'green',
  },
  {
    id: 'rc-3',
    staffName: 'James Carter',
    changeDescription: 'Invitation resent',
    timestamp: 'Jun 11, 2025 11:46 AM',
    dotColor: 'blue',
  },
  {
    id: 'rc-4',
    staffName: 'Ananya Iyer',
    changeDescription: 'Added to Health Information',
    timestamp: 'Jun 10, 2025 03:28 PM',
    dotColor: 'green',
  },
];
