import {
  VerificationStats,
  DoctorVerificationApplication,
  VerificationActivityLog,
} from './verificationTypes';

export const mockVerificationStats: VerificationStats = {
  pendingReviews: 8,
  pendingTrend: '↑ 2',
  approvedToday: 5,
  approvedTrend: '↑ 25%',
  rejected: 2,
  rejectedTrend: '↑ 1',
  needMoreInfo: 3,
  needMoreInfoTrend: '↑ 1',
};

export const mockVerificationApplications: DoctorVerificationApplication[] = [
  {
    id: 'app-01',
    doctorName: 'Dr. Priya Sharma',
    avatar: '/doc_priya_sharma.png',
    degrees: 'MBBS, MD (Cardiology), DM (Cardiology)',
    specialty: 'Cardiology',
    department: 'Cardiology',
    licenseId: 'MED784521',
    submittedOn: 'Jun 11, 2025',
    documentsStatus: 'Complete',
    backgroundCheck: 'Clear',
    status: 'Pending',
    qualifications: [
      {
        degree: 'MBBS',
        institute: 'All India Institute of Medical Sciences',
        year: '2012',
      },
      {
        degree: 'MD - Internal Medicine',
        institute: 'AIIMS',
        year: '2015',
      },
      {
        degree: 'DM - Cardiology',
        institute: 'PGI, Chandigarh',
        year: '2018',
      },
    ],
    uploadedDocs: [
      { name: 'Medical Degree Certificate', format: 'PDF' },
      { name: 'Postgraduate Degree Certificate', format: 'PDF' },
      { name: 'Medical Council License', format: 'PDF' },
      { name: 'Experience Certificate', format: 'PDF' },
      { name: 'Identity Proof (Aadhaar)', format: 'PDF' },
    ],
    licenseDetail: {
      licenseId: 'MED784521',
      issuingAuthority: 'Medical Council of India',
      validFrom: 'Jan 10, 2023',
      validUntil: 'Jan 10, 2028',
      remainingText: '2 years remaining',
      isValid: true,
    },
  },
  {
    id: 'app-02',
    doctorName: 'Dr. Arjun Mehta',
    avatar: '/doc_avatar_2.png',
    degrees: 'MBBS, MD (Radiology)',
    specialty: 'Radiology',
    department: 'Radiology',
    licenseId: 'MED332112',
    submittedOn: 'Jun 10, 2025',
    documentsStatus: 'Complete',
    backgroundCheck: 'Clear',
    status: 'Pending',
    qualifications: [
      {
        degree: 'MBBS',
        institute: 'Maulana Azad Medical College, New Delhi',
        year: '2014',
      },
      {
        degree: 'MD - Radiodiagnosis',
        institute: 'Lady Hardinge Medical College',
        year: '2018',
      },
    ],
    uploadedDocs: [
      { name: 'Medical Degree Certificate', format: 'PDF' },
      { name: 'Postgraduate Degree Certificate', format: 'PDF' },
      { name: 'State Medical Council Registration', format: 'PDF' },
      { name: 'Aadhaar Card Copy', format: 'PDF' },
    ],
    licenseDetail: {
      licenseId: 'MED332112',
      issuingAuthority: 'Delhi Medical Council',
      validFrom: 'Mar 15, 2022',
      validUntil: 'Mar 15, 2027',
      remainingText: '1.5 years remaining',
      isValid: true,
    },
  },
  {
    id: 'app-03',
    doctorName: 'Dr. Neha Kapoor',
    avatar: '/doc_avatar_3.png',
    degrees: 'MBBS, DM (Neurology)',
    specialty: 'Neurology',
    department: 'Neurology',
    licenseId: 'MED667890',
    submittedOn: 'Jun 9, 2025',
    documentsStatus: 'Missing (1)',
    backgroundCheck: 'In Progress',
    status: 'Pending',
    qualifications: [
      {
        degree: 'MBBS',
        institute: 'King George’s Medical University, Lucknow',
        year: '2013',
      },
      {
        degree: 'MD - General Medicine',
        institute: 'KGMU',
        year: '2016',
      },
      {
        degree: 'DM - Neurology',
        institute: 'NIMHANS, Bangalore',
        year: '2019',
      },
    ],
    uploadedDocs: [
      { name: 'Medical Degree Certificate', format: 'PDF' },
      { name: 'Medical Council License', format: 'PDF' },
      { name: 'Identity Proof', format: 'PDF' },
    ],
    licenseDetail: {
      licenseId: 'MED667890',
      issuingAuthority: 'Uttar Pradesh Medical Council',
      validFrom: 'Aug 12, 2021',
      validUntil: 'Aug 12, 2026',
      remainingText: '1 year remaining',
      isValid: true,
    },
  },
  {
    id: 'app-04',
    doctorName: 'Dr. Sameer Khan',
    avatar: '/doc_avatar_4.png',
    degrees: 'MBBS, MD (Emergency Medicine)',
    specialty: 'Emergency Medicine',
    department: 'Emergency',
    licenseId: 'MED445678',
    submittedOn: 'Jun 9, 2025',
    documentsStatus: 'Complete',
    backgroundCheck: 'Clear',
    status: 'Pending',
    qualifications: [
      {
        degree: 'MBBS',
        institute: 'Grant Medical College, Mumbai',
        year: '2015',
      },
      {
        degree: 'MD - Emergency Medicine',
        institute: 'AIIMS, Rishikesh',
        year: '2019',
      },
    ],
    uploadedDocs: [
      { name: 'Medical Degree Certificate', format: 'PDF' },
      { name: 'Emergency Residency Certificate', format: 'PDF' },
      { name: 'Medical Council License', format: 'PDF' },
      { name: 'Identity Proof', format: 'PDF' },
    ],
    licenseDetail: {
      licenseId: 'MED445678',
      issuingAuthority: 'Maharashtra Medical Council',
      validFrom: 'May 05, 2022',
      validUntil: 'May 05, 2027',
      remainingText: '1.8 years remaining',
      isValid: true,
    },
  },
  {
    id: 'app-05',
    doctorName: 'Dr. Ananya Iyer',
    avatar: '/doc_avatar_5.png',
    degrees: 'MBBS, MD (General Medicine)',
    specialty: 'General Medicine',
    department: 'General Medicine',
    licenseId: 'MED998761',
    submittedOn: 'Jun 8, 2025',
    documentsStatus: 'Complete',
    backgroundCheck: 'Clear',
    status: 'Pending',
    qualifications: [
      {
        degree: 'MBBS',
        institute: 'Madras Medical College, Chennai',
        year: '2016',
      },
      {
        degree: 'MD - General Medicine',
        institute: 'JIPMER, Puducherry',
        year: '2020',
      },
    ],
    uploadedDocs: [
      { name: 'Medical Degree Certificate', format: 'PDF' },
      { name: 'Postgraduate Certificate', format: 'PDF' },
      { name: 'Tamil Nadu Medical Council Reg', format: 'PDF' },
      { name: 'Identity Proof (Passport)', format: 'PDF' },
    ],
    licenseDetail: {
      licenseId: 'MED998761',
      issuingAuthority: 'Tamil Nadu Medical Council',
      validFrom: 'Feb 20, 2023',
      validUntil: 'Feb 20, 2028',
      remainingText: '2.5 years remaining',
      isValid: true,
    },
  },
  {
    id: 'app-06',
    doctorName: 'Dr. Rohan Malhotra',
    avatar: '/doc_avatar_6.png',
    degrees: 'MBBS, MS (Orthopedics)',
    specialty: 'Orthopedics',
    department: 'Orthopedics',
    licenseId: 'MED776543',
    submittedOn: 'Jun 8, 2025',
    documentsStatus: 'Missing (2)',
    backgroundCheck: 'Not Started',
    status: 'Pending',
    qualifications: [
      {
        degree: 'MBBS',
        institute: 'Christian Medical College, Ludhiana',
        year: '2011',
      },
      {
        degree: 'MS - Orthopedic Surgery',
        institute: 'PGIMER, Chandigarh',
        year: '2015',
      },
    ],
    uploadedDocs: [
      { name: 'Medical Degree Certificate', format: 'PDF' },
      { name: 'Identity Proof', format: 'PDF' },
    ],
    licenseDetail: {
      licenseId: 'MED776543',
      issuingAuthority: 'Punjab Medical Council',
      validFrom: 'Sep 10, 2020',
      validUntil: 'Sep 10, 2025',
      remainingText: '3 months remaining',
      isValid: true,
    },
  },
  {
    id: 'app-07',
    doctorName: 'Dr. Kavita Rao',
    avatar: '/doc_avatar_7.png',
    degrees: 'MBBS, MD (Pediatrics)',
    specialty: 'Pediatrics',
    department: 'Pediatrics',
    licenseId: 'MED881214',
    submittedOn: 'Jun 7, 2025',
    documentsStatus: 'Complete',
    backgroundCheck: 'Clear',
    status: 'Pending',
    qualifications: [
      {
        degree: 'MBBS',
        institute: 'Bangalore Medical College',
        year: '2013',
      },
      {
        degree: 'MD - Pediatrics',
        institute: 'St. John’s Medical College, Bangalore',
        year: '2017',
      },
    ],
    uploadedDocs: [
      { name: 'MBBS Degree Certificate', format: 'PDF' },
      { name: 'Pediatrics MD Degree', format: 'PDF' },
      { name: 'Karnataka Medical Council Certificate', format: 'PDF' },
      { name: 'Aadhaar Card Copy', format: 'PDF' },
    ],
    licenseDetail: {
      licenseId: 'MED881214',
      issuingAuthority: 'Karnataka Medical Council',
      validFrom: 'Nov 14, 2021',
      validUntil: 'Nov 14, 2026',
      remainingText: '1.2 years remaining',
      isValid: true,
    },
  },
  {
    id: 'app-08',
    doctorName: 'Dr. Vikram Singh',
    avatar: '/doc_avatar_8.png',
    degrees: 'MBBS, MD (Radiation Oncology)',
    specialty: 'Oncology',
    department: 'Oncology',
    licenseId: 'MED771223',
    submittedOn: 'Jun 7, 2025',
    documentsStatus: 'Complete',
    backgroundCheck: 'In Progress',
    status: 'Pending',
    qualifications: [
      {
        degree: 'MBBS',
        institute: 'Armed Forces Medical College, Pune',
        year: '2015',
      },
      {
        degree: 'MD - Radiation Oncology',
        institute: 'Tata Memorial Hospital, Mumbai',
        year: '2019',
      },
    ],
    uploadedDocs: [
      { name: 'Medical Degree Certificate', format: 'PDF' },
      { name: 'Oncology Fellowship Certificate', format: 'PDF' },
      { name: 'State Medical License', format: 'PDF' },
      { name: 'Identity Proof', format: 'PDF' },
    ],
    licenseDetail: {
      licenseId: 'MED771223',
      issuingAuthority: 'Maharashtra Medical Council',
      validFrom: 'Jan 05, 2023',
      validUntil: 'Jan 05, 2028',
      remainingText: '2.5 years remaining',
      isValid: true,
    },
  },
];

export const mockVerificationActivity: VerificationActivityLog[] = [
  {
    id: 'act-01',
    user: 'Dr. Amit Verma',
    doctorName: 'Dr. Rohan Malhotra',
    action: 'Requested More Info',
    timestamp: 'Jun 12, 2025 09:24 AM',
  },
  {
    id: 'act-02',
    user: 'Nurse Sarah Wilson',
    doctorName: 'Dr. Kavita Rao',
    action: 'Approved',
    timestamp: 'Jun 12, 2025 08:17 AM',
  },
  {
    id: 'act-03',
    user: 'Dr. Vikram Singh',
    doctorName: 'Dr. Sameer Khan',
    action: 'Approved',
    timestamp: 'Jun 12, 2025 07:56 AM',
  },
  {
    id: 'act-04',
    user: 'Admin (Priya Nair)',
    doctorName: 'Dr. Arjun Mehta',
    action: 'Rejected',
    timestamp: 'Jun 11, 2025 04:32 PM',
  },
  {
    id: 'act-05',
    user: 'IT Support (Rohan)',
    doctorName: 'Dr. Neha Kapoor',
    action: 'Requested More Info',
    timestamp: 'Jun 11, 2025 11:42 AM',
  },
];
