import {
  MyPatientItem,
  MyPatientsStats,
  UpcomingFollowupItem,
} from './myPatientsTypes';

export const mockMyPatientsStats: MyPatientsStats = {
  totalPatients: 48,
  totalPatientsTrend: '↑ 12% from last month',
  activeTreatments: 16,
  activeTreatmentsSubtitle: 'Ongoing care',
  followupsDue: 28,
  followupsDueSubtitle: 'In next 7 days',
  newThisMonth: 6,
  newThisMonthTrend: '↑ 20% from last month',
};

export const mockMyPatientsList: MyPatientItem[] = [
  {
    id: 'pat-1',
    rowNum: 1,
    name: 'Rohit Sharma',
    avatarUrl: '/doc_avatar_1.png',
    uhid: 'MLK00123',
    healthId: '91-2345-6789-1234',
    age: 45,
    gender: 'M',
    primaryCondition: 'Type 2 Diabetes',
    lastVisit: '12 Sep 2026',
    status: 'Active',
    phone: '+91 98765 43210',
    email: 'rohit.sharma@example.com',
    bloodGroup: 'B+',
  },
  {
    id: 'pat-2',
    rowNum: 2,
    name: 'Neha Verma',
    avatarUrl: '/doc_avatar_2.png',
    uhid: 'MLK00456',
    healthId: '91-2345-6789-5678',
    age: 29,
    gender: 'F',
    primaryCondition: 'Hypertension',
    lastVisit: '10 Sep 2026',
    status: 'Active',
    phone: '+91 98112 34567',
    email: 'neha.verma@example.com',
    bloodGroup: 'O+',
  },
  {
    id: 'pat-3',
    rowNum: 3,
    name: 'Amit Kumar',
    avatarUrl: '/doc_avatar_3.png',
    uhid: 'MLK00789',
    healthId: '91-2345-6789-9012',
    age: 62,
    gender: 'M',
    primaryCondition: 'Cardiac Care',
    lastVisit: '05 Sep 2026',
    status: 'Follow-up Due',
    phone: '+91 99223 34455',
    email: 'amit.kumar@example.com',
    bloodGroup: 'A+',
  },
  {
    id: 'pat-4',
    rowNum: 4,
    name: 'Priya Singh',
    avatarUrl: '/doc_avatar_4.png',
    uhid: 'MLK00987',
    healthId: '91-2345-6789-1357',
    age: 33,
    gender: 'F',
    primaryCondition: 'Asthma',
    lastVisit: '02 Sep 2026',
    status: 'Active',
    phone: '+91 97123 45678',
    email: 'priya.singh@example.com',
    bloodGroup: 'AB+',
  },
  {
    id: 'pat-5',
    rowNum: 5,
    name: 'Vikas Mehta',
    avatarUrl: '/doc_avatar_5.png',
    uhid: 'MLK01122',
    healthId: '91-2345-6789-2468',
    age: 37,
    gender: 'M',
    primaryCondition: 'Orthopedics',
    lastVisit: '28 Aug 2026',
    status: 'Active',
    phone: '+91 98334 55667',
    email: 'vikas.mehta@example.com',
    bloodGroup: 'O-',
  },
  {
    id: 'pat-6',
    rowNum: 6,
    name: 'Kavya Sharma',
    avatarUrl: '/doc_avatar_6.png',
    uhid: 'MLK01333',
    healthId: '91-2345-6789-9753',
    age: 27,
    gender: 'F',
    primaryCondition: 'Thyroid Disorder',
    lastVisit: '25 Aug 2026',
    status: 'Needs Review',
    phone: '+91 98998 77665',
    email: 'kavya.sharma@example.com',
    bloodGroup: 'B-',
  },
  {
    id: 'pat-7',
    rowNum: 7,
    name: 'Suresh Gupta',
    avatarUrl: '/doc_avatar_7.png',
    uhid: 'MLK01544',
    healthId: '91-2345-6789-8642',
    age: 51,
    gender: 'M',
    primaryCondition: 'COPD',
    lastVisit: '20 Aug 2026',
    status: 'Follow-up Due',
    phone: '+91 98450 12345',
    email: 'suresh.gupta@example.com',
    bloodGroup: 'A-',
  },
  {
    id: 'pat-8',
    rowNum: 8,
    name: 'Anjali Mehra',
    avatarUrl: '/doc_avatar_8.png',
    uhid: 'MLK01755',
    healthId: '91-2345-6789-1111',
    age: 41,
    gender: 'F',
    primaryCondition: 'Migraine',
    lastVisit: '18 Aug 2026',
    status: 'Active',
    phone: '+91 99001 23456',
    email: 'anjali.mehra@example.com',
    bloodGroup: 'O+',
  },
];

export const mockUpcomingFollowups: UpcomingFollowupItem[] = [
  {
    id: 'fu-1',
    name: 'Neha Verma',
    avatarUrl: '/doc_avatar_2.png',
    reason: 'Diabetes follow-up',
    dueDate: '17 Sep 2026',
  },
  {
    id: 'fu-2',
    name: 'Amit Kumar',
    avatarUrl: '/doc_avatar_3.png',
    reason: 'Cardiology review',
    dueDate: '18 Sep 2026',
  },
  {
    id: 'fu-3',
    name: 'Suresh Gupta',
    avatarUrl: '/doc_avatar_7.png',
    reason: 'Lab results discussion',
    dueDate: '19 Sep 2026',
  },
  {
    id: 'fu-4',
    name: 'Kavya Sharma',
    avatarUrl: '/doc_avatar_6.png',
    reason: 'Thyroid review',
    dueDate: '20 Sep 2026',
  },
];
