import { PatientSearchResultItem, RecentSearchItem } from './patientSearchTypes';

export const mockPatientSearchResults: PatientSearchResultItem[] = [
  {
    id: 'pat-1',
    name: 'Rohit Sharma',
    uhid: 'MLK00123',
    healthId: '91-2345-6789-1234',
    age: 45,
    gender: 'M',
    lastVisitDate: '12 Sep 2026',
    lastVisitDepartment: 'General Medicine',
    accessStatus: 'Authorized',
    phone: '+91 98765 43210',
    bloodGroup: 'B+',
    allergies: ['Penicillin', 'Sulfa drugs'],
    recentCondition: 'Type 2 Diabetes Mellitus with peripheral neuropathy checkup',
  },
  {
    id: 'pat-2',
    name: 'Neha Sharma',
    uhid: 'MLK00456',
    healthId: '91-2345-6789-5678',
    age: 29,
    gender: 'F',
    lastVisitDate: '10 Sep 2026',
    lastVisitDepartment: 'Consultation',
    accessStatus: 'Request Access',
    phone: '+91 98112 34567',
    bloodGroup: 'O+',
    allergies: ['None reported'],
    recentCondition: 'Acute viral upper respiratory tract infection',
  },
  {
    id: 'pat-3',
    name: 'Amit Sharma',
    uhid: 'MLK00789',
    healthId: '91-2345-6789-9012',
    age: 62,
    gender: 'M',
    lastVisitDate: '05 Sep 2026',
    lastVisitDepartment: 'Cardiology',
    accessStatus: 'Authorized',
    phone: '+91 99223 34455',
    bloodGroup: 'A+',
    allergies: ['Aspirin (Mild GI distress)'],
    recentCondition: 'Coronary Artery Disease with post-angioplasty follow-up',
  },
  {
    id: 'pat-4',
    name: 'Kavya Sharma',
    uhid: 'MLK01011',
    healthId: '91-2345-6789-3456',
    age: 8,
    gender: 'F',
    lastVisitDate: '28 Aug 2026',
    lastVisitDepartment: 'Pediatrics',
    accessStatus: 'Authorized',
    phone: '+91 97123 45678',
    bloodGroup: 'B+',
    allergies: ['Peanuts'],
    recentCondition: 'Childhood Asthma and seasonal allergic rhinitis',
  },
  {
    id: 'pat-5',
    name: 'Vikas Sharma',
    uhid: 'MLK01122',
    healthId: '91-2345-6789-7890',
    age: 37,
    gender: 'M',
    lastVisitDate: '20 Aug 2026',
    lastVisitDepartment: 'Orthopedics',
    accessStatus: 'Pending',
    phone: '+91 98456 78901',
    bloodGroup: 'AB+',
    allergies: ['None reported'],
    recentCondition: 'Right knee anterior cruciate ligament (ACL) sprain rehabilitation',
  },
  {
    id: 'pat-6',
    name: 'Priya Sharma',
    uhid: 'MLK01333',
    healthId: '91-2345-6789-1357',
    age: 33,
    gender: 'F',
    lastVisitDate: '18 Aug 2026',
    lastVisitDepartment: 'General Medicine',
    accessStatus: 'Authorized',
    phone: '+91 98654 32198',
    bloodGroup: 'O-',
    allergies: ['Latex'],
    recentCondition: 'Hypothyroidism on Levothyroxine replacement therapy',
  },
  {
    id: 'pat-7',
    name: 'Suresh Sharma',
    uhid: 'MLK01544',
    healthId: '91-2345-6789-2468',
    age: 51,
    gender: 'M',
    lastVisitDate: '12 Aug 2026',
    lastVisitDepartment: 'Pulmonology',
    accessStatus: 'Access Denied',
    phone: '+91 97890 12345',
    bloodGroup: 'A-',
    allergies: ['NSAIDs'],
    recentCondition: 'Chronic Obstructive Pulmonary Disease (COPD) Grade 2',
  },
  {
    id: 'pat-8',
    name: 'Anjali Sharma',
    uhid: 'MLK01755',
    healthId: '91-2345-6789-9753',
    age: 27,
    gender: 'F',
    lastVisitDate: '03 Aug 2026',
    lastVisitDepartment: 'Dermatology',
    accessStatus: 'Request Access',
    phone: '+91 98234 56789',
    bloodGroup: 'B-',
    allergies: ['Nickel contact dermatitis'],
    recentCondition: 'Atopic dermatitis flare-up managed with topical steroids',
  },
  // Page 2 Mock Patients
  {
    id: 'pat-9',
    name: 'Manish Sharma',
    uhid: 'MLK01889',
    healthId: '91-2345-6789-8899',
    age: 42,
    gender: 'M',
    lastVisitDate: '25 Jul 2026',
    lastVisitDepartment: 'Neurology',
    accessStatus: 'Authorized',
    phone: '+91 98345 67890',
    bloodGroup: 'O+',
    allergies: ['None'],
    recentCondition: 'Migraine with aura prophylactic management',
  },
  {
    id: 'pat-10',
    name: 'Sunita Sharma',
    uhid: 'MLK01990',
    healthId: '91-2345-6789-9900',
    age: 58,
    gender: 'F',
    lastVisitDate: '19 Jul 2026',
    lastVisitDepartment: 'Endocrinology',
    accessStatus: 'Authorized',
    phone: '+91 98456 12345',
    bloodGroup: 'A+',
    allergies: ['Iodine'],
    recentCondition: 'Osteoporosis and Vitamin D deficiency maintenance',
  },
  {
    id: 'pat-11',
    name: 'Rakesh Sharma',
    uhid: 'MLK02001',
    healthId: '91-2345-6789-0011',
    age: 31,
    gender: 'M',
    lastVisitDate: '10 Jul 2026',
    lastVisitDepartment: 'ENT',
    accessStatus: 'Pending',
    phone: '+91 98567 23456',
    bloodGroup: 'B+',
    allergies: ['None'],
    recentCondition: 'Chronic sinusitis post-antrostomy checkup',
  },
  {
    id: 'pat-12',
    name: 'Pooja Sharma',
    uhid: 'MLK02112',
    healthId: '91-2345-6789-1122',
    age: 24,
    gender: 'F',
    lastVisitDate: '02 Jul 2026',
    lastVisitDepartment: 'Ophthalmology',
    accessStatus: 'Authorized',
    phone: '+91 98678 34567',
    bloodGroup: 'AB-',
    allergies: ['Ciprofloxacin eye drops'],
    recentCondition: 'High myopia refractive evaluation',
  },
];

export const mockRecentSearches: RecentSearchItem[] = [
  {
    id: 'rec-1',
    query: 'Rohit Sharma',
    displayDetail: 'UHID: MLK00123',
    timeAgo: '5 min ago',
    type: 'name',
  },
  {
    id: 'rec-2',
    query: 'Neha Verma',
    displayDetail: 'Phone: +91 98765 43210',
    timeAgo: '12 min ago',
    type: 'phone',
  },
  {
    id: 'rec-3',
    query: 'Amit Kumar',
    displayDetail: 'Health ID: 91-2345-6789-9012',
    timeAgo: '1 hour ago',
    type: 'health-id',
  },
  {
    id: 'rec-4',
    query: 'Priya Singh',
    displayDetail: 'UHID: MLK00456',
    timeAgo: '2 hours ago',
    type: 'uhid',
  },
  {
    id: 'rec-5',
    query: 'Vikas Mehta',
    displayDetail: 'Phone: +91 87654 32109',
    timeAgo: '3 hours ago',
    type: 'phone',
  },
];
